apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc-pod
  template:
    metadata:
      labels:
        app: svc-pod
    spec:
      containers:
      - name: flask
        image: shmuela6/devops_course
        ports:
        - containerPort: 80


