apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-1
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-1
  template:
    metadata:
      labels:
        app: python-1
    spec:
      containers:
      - name: python-1
        image: shmuela6:devops_course